### PR TITLE
Added 2 more reasons to report a job.

### PR DESCRIPTION
**Pull request by frankdejonge**
I want more boxed to put my complaints in.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@rdohms I just noticed, this is still open ... Y U NO LIKE ME

**Comment by rdohms** [comment]
@FrenkyNet, i have not yet taken over this project, @pascaldevink is the one that does not like you.

**Comment by frankdejonge** [comment]
@pascaldevink PASCAAAAAALLLL my bald bro, get cracking with the merge dog. Peace :neckbeard:

**Comment by pascaldevink** [comment]
I'm gonna merge it, but it's not gonna be live until we revamp the job board :crying_cat_face: 
Mainly, I think we need to implement the same style as the website @rdohms made.

**Pull request merged**
