### PR TITLE
first try at a job board

### PR DESCRIPTION
**Pull request by francodacosta**
I had some free time and decided to hack something together mostly because I can really attend hackatons and this might help to move things forward

this is the bare minimal job board.

user registration
job ad CRUD

this is based on symfony 2.2 and has the normal install process
1) pull deps with composer
2) create database with doctrine

let me know what you guys think

nuno

### CODE REVIEW

**Comment by francodacosta** [comment]
anyone ?

**Comment by rdohms** [comment]
@francodacosta what version of Apache are you using? it seems my apache does not understand the .htaccess

**Comment by rdohms** [comment]
Seems like a good start to me, but we still need to flesh out the details of how we want stuff to be.
I think it needs: 
- install instructions added to README
- parameters.yml.dist for bootstrapping it

Other then that it seems like a good start, i'll take a look at the code later.

**Comment by francodacosta** [comment]
@rdohms  Have you sort out the htaccess stuff?

I'm running apache 2.4.3 and developing on a virtual host

It still needs lots of stuff, I had an afternoon "free" at work and decided to play a bit with symfony.

I'm amazed at how much can be automatically generated

**Comment by rdohms** [comment]
@francodacosta i had to remove the [END] rules, would be good to keep the original .htaccess from symfony-standard. 

Yeah it can generate a lot, we should eventually refactor that, but its a nice head start.

**Comment by francodacosta** [comment]
I don't remember touching the htaccess

Maybe it is because I'm using 2.2 beta and they changed it

**Comment by rdohms** [comment]
@francodacosta yeah it does not look at all like: https://github.com/symfony/symfony-standard/blob/2.2/web/.htaccess

**Comment by francodacosta** [comment]
That's the problem with unstable versions, 
https://github.com/symfony/symfony-standard/blob/b46c01a8265c3c79803e031725441aaf94b1f1a4/web/.htaccess 
(22 feb 2013)

**Comment by pascaldevink** [comment]
I'll check it out as soon as I have time (somewhere this weekend), but this should serve as a great start!

**Pull request merged**
